// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// sim_pwc_recruitment_cpp
NumericVector sim_pwc_recruitment_cpp(NumericVector rates, NumericVector periods, int n);
RcppExport SEXP _appendMCP_sim_pwc_recruitment_cpp(SEXP ratesSEXP, SEXP periodsSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type rates(ratesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type periods(periodsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(sim_pwc_recruitment_cpp(rates, periods, n));
    return rcpp_result_gen;
END_RCPP
}
// sim_pwc_stratified_recruitment_cpp
DataFrame sim_pwc_stratified_recruitment_cpp(DataFrame enroll_rate, int n, Nullable<IntegerVector> n_min_per_stratum, Nullable<IntegerVector> n_max_per_stratum);
RcppExport SEXP _appendMCP_sim_pwc_stratified_recruitment_cpp(SEXP enroll_rateSEXP, SEXP nSEXP, SEXP n_min_per_stratumSEXP, SEXP n_max_per_stratumSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type enroll_rate(enroll_rateSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type n_min_per_stratum(n_min_per_stratumSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type n_max_per_stratum(n_max_per_stratumSEXP);
    rcpp_result_gen = Rcpp::wrap(sim_pwc_stratified_recruitment_cpp(enroll_rate, n, n_min_per_stratum, n_max_per_stratum));
    return rcpp_result_gen;
END_RCPP
}
// sim_pb_randomization_cpp
DataFrame sim_pb_randomization_cpp(DataFrame enroll_data, DataFrame enroll_rate);
RcppExport SEXP _appendMCP_sim_pb_randomization_cpp(SEXP enroll_dataSEXP, SEXP enroll_rateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type enroll_data(enroll_dataSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type enroll_rate(enroll_rateSEXP);
    rcpp_result_gen = Rcpp::wrap(sim_pb_randomization_cpp(enroll_data, enroll_rate));
    return rcpp_result_gen;
END_RCPP
}
// events_at_time_cpp
int events_at_time_cpp(DataFrame df, double time, std::string ep, Nullable<CharacterVector> strata);
RcppExport SEXP _appendMCP_events_at_time_cpp(SEXP dfSEXP, SEXP timeSEXP, SEXP epSEXP, SEXP strataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< double >::type time(timeSEXP);
    Rcpp::traits::input_parameter< std::string >::type ep(epSEXP);
    Rcpp::traits::input_parameter< Nullable<CharacterVector> >::type strata(strataSEXP);
    rcpp_result_gen = Rcpp::wrap(events_at_time_cpp(df, time, ep, strata));
    return rcpp_result_gen;
END_RCPP
}
// time_at_events_cpp
double time_at_events_cpp(DataFrame df, int events, std::string ep, Nullable<CharacterVector> strata);
RcppExport SEXP _appendMCP_time_at_events_cpp(SEXP dfSEXP, SEXP eventsSEXP, SEXP epSEXP, SEXP strataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< int >::type events(eventsSEXP);
    Rcpp::traits::input_parameter< std::string >::type ep(epSEXP);
    Rcpp::traits::input_parameter< Nullable<CharacterVector> >::type strata(strataSEXP);
    rcpp_result_gen = Rcpp::wrap(time_at_events_cpp(df, events, ep, strata));
    return rcpp_result_gen;
END_RCPP
}
// recruited_at_time_cpp
int recruited_at_time_cpp(DataFrame df, double time, Nullable<CharacterVector> strata);
RcppExport SEXP _appendMCP_recruited_at_time_cpp(SEXP dfSEXP, SEXP timeSEXP, SEXP strataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< double >::type time(timeSEXP);
    Rcpp::traits::input_parameter< Nullable<CharacterVector> >::type strata(strataSEXP);
    rcpp_result_gen = Rcpp::wrap(recruited_at_time_cpp(df, time, strata));
    return rcpp_result_gen;
END_RCPP
}
// time_at_recruited_cpp
double time_at_recruited_cpp(DataFrame df, int recruited, Nullable<CharacterVector> strata);
RcppExport SEXP _appendMCP_time_at_recruited_cpp(SEXP dfSEXP, SEXP recruitedSEXP, SEXP strataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< int >::type recruited(recruitedSEXP);
    Rcpp::traits::input_parameter< Nullable<CharacterVector> >::type strata(strataSEXP);
    rcpp_result_gen = Rcpp::wrap(time_at_recruited_cpp(df, recruited, strata));
    return rcpp_result_gen;
END_RCPP
}
// responses_at_time_cpp
int responses_at_time_cpp(DataFrame df, double time, std::string ep, Nullable<CharacterVector> strata);
RcppExport SEXP _appendMCP_responses_at_time_cpp(SEXP dfSEXP, SEXP timeSEXP, SEXP epSEXP, SEXP strataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< double >::type time(timeSEXP);
    Rcpp::traits::input_parameter< std::string >::type ep(epSEXP);
    Rcpp::traits::input_parameter< Nullable<CharacterVector> >::type strata(strataSEXP);
    rcpp_result_gen = Rcpp::wrap(responses_at_time_cpp(df, time, ep, strata));
    return rcpp_result_gen;
END_RCPP
}
// time_at_responses_cpp
double time_at_responses_cpp(DataFrame df, int responses, std::string ep, Nullable<CharacterVector> strata);
RcppExport SEXP _appendMCP_time_at_responses_cpp(SEXP dfSEXP, SEXP responsesSEXP, SEXP epSEXP, SEXP strataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< int >::type responses(responsesSEXP);
    Rcpp::traits::input_parameter< std::string >::type ep(epSEXP);
    Rcpp::traits::input_parameter< Nullable<CharacterVector> >::type strata(strataSEXP);
    rcpp_result_gen = Rcpp::wrap(time_at_responses_cpp(df, responses, ep, strata));
    return rcpp_result_gen;
END_RCPP
}
// test_pooled_proportions_cpp
NumericVector test_pooled_proportions_cpp(DataFrame df, std::string endpoint, CharacterVector strata, std::string control, std::string test);
RcppExport SEXP _appendMCP_test_pooled_proportions_cpp(SEXP dfSEXP, SEXP endpointSEXP, SEXP strataSEXP, SEXP controlSEXP, SEXP testSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< std::string >::type endpoint(endpointSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type strata(strataSEXP);
    Rcpp::traits::input_parameter< std::string >::type control(controlSEXP);
    Rcpp::traits::input_parameter< std::string >::type test(testSEXP);
    rcpp_result_gen = Rcpp::wrap(test_pooled_proportions_cpp(df, endpoint, strata, control, test));
    return rcpp_result_gen;
END_RCPP
}
// test_unpooled_proportions_cpp
NumericVector test_unpooled_proportions_cpp(DataFrame df, std::string endpoint, CharacterVector strata, std::string control, std::string test);
RcppExport SEXP _appendMCP_test_unpooled_proportions_cpp(SEXP dfSEXP, SEXP endpointSEXP, SEXP strataSEXP, SEXP controlSEXP, SEXP testSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< std::string >::type endpoint(endpointSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type strata(strataSEXP);
    Rcpp::traits::input_parameter< std::string >::type control(controlSEXP);
    Rcpp::traits::input_parameter< std::string >::type test(testSEXP);
    rcpp_result_gen = Rcpp::wrap(test_unpooled_proportions_cpp(df, endpoint, strata, control, test));
    return rcpp_result_gen;
END_RCPP
}
// test_logrank_cpp
NumericVector test_logrank_cpp(DataFrame df, std::string endpoint, CharacterVector strata, std::string control, std::string test);
RcppExport SEXP _appendMCP_test_logrank_cpp(SEXP dfSEXP, SEXP endpointSEXP, SEXP strataSEXP, SEXP controlSEXP, SEXP testSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< std::string >::type endpoint(endpointSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type strata(strataSEXP);
    Rcpp::traits::input_parameter< std::string >::type control(controlSEXP);
    Rcpp::traits::input_parameter< std::string >::type test(testSEXP);
    rcpp_result_gen = Rcpp::wrap(test_logrank_cpp(df, endpoint, strata, control, test));
    return rcpp_result_gen;
END_RCPP
}
// test_stratified_logrank_cpp
NumericVector test_stratified_logrank_cpp(DataFrame df, std::string endpoint, CharacterVector strata, std::string control, std::string test);
RcppExport SEXP _appendMCP_test_stratified_logrank_cpp(SEXP dfSEXP, SEXP endpointSEXP, SEXP strataSEXP, SEXP controlSEXP, SEXP testSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< std::string >::type endpoint(endpointSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type strata(strataSEXP);
    Rcpp::traits::input_parameter< std::string >::type control(controlSEXP);
    Rcpp::traits::input_parameter< std::string >::type test(testSEXP);
    rcpp_result_gen = Rcpp::wrap(test_stratified_logrank_cpp(df, endpoint, strata, control, test));
    return rcpp_result_gen;
END_RCPP
}
// test_cmh_cpp
NumericVector test_cmh_cpp(DataFrame df, std::string endpoint, CharacterVector strata, std::string control, std::string test);
RcppExport SEXP _appendMCP_test_cmh_cpp(SEXP dfSEXP, SEXP endpointSEXP, SEXP strataSEXP, SEXP controlSEXP, SEXP testSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< std::string >::type endpoint(endpointSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type strata(strataSEXP);
    Rcpp::traits::input_parameter< std::string >::type control(controlSEXP);
    Rcpp::traits::input_parameter< std::string >::type test(testSEXP);
    rcpp_result_gen = Rcpp::wrap(test_cmh_cpp(df, endpoint, strata, control, test));
    return rcpp_result_gen;
END_RCPP
}
// cut_data_at_time_cpp
DataFrame cut_data_at_time_cpp(DataFrame df, double time);
RcppExport SEXP _appendMCP_cut_data_at_time_cpp(SEXP dfSEXP, SEXP timeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< double >::type time(timeSEXP);
    rcpp_result_gen = Rcpp::wrap(cut_data_at_time_cpp(df, time));
    return rcpp_result_gen;
END_RCPP
}
// update_graph_cpp
List update_graph_cpp(NumericMatrix edges, NumericVector weights, int rejected);
RcppExport SEXP _appendMCP_update_graph_cpp(SEXP edgesSEXP, SEXP weightsSEXP, SEXP rejectedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type edges(edgesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< int >::type rejected(rejectedSEXP);
    rcpp_result_gen = Rcpp::wrap(update_graph_cpp(edges, weights, rejected));
    return rcpp_result_gen;
END_RCPP
}
// update_p_thresholds_cpp
NumericMatrix update_p_thresholds_cpp(DataFrame analyses, DataFrame hypotheses, NumericMatrix edges, NumericVector weights);
RcppExport SEXP _appendMCP_update_p_thresholds_cpp(SEXP analysesSEXP, SEXP hypothesesSEXP, SEXP edgesSEXP, SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type analyses(analysesSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type hypotheses(hypothesesSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type edges(edgesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(update_p_thresholds_cpp(analyses, hypotheses, edges, weights));
    return rcpp_result_gen;
END_RCPP
}
// get_maurer_bretz_z_raw_cpp
NumericMatrix get_maurer_bretz_z_raw_cpp(NumericVector pvec, DataFrame analyses, DataFrame hypotheses, NumericMatrix edges, NumericVector weights);
RcppExport SEXP _appendMCP_get_maurer_bretz_z_raw_cpp(SEXP pvecSEXP, SEXP analysesSEXP, SEXP hypothesesSEXP, SEXP edgesSEXP, SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pvec(pvecSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type analyses(analysesSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type hypotheses(hypothesesSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type edges(edgesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(get_maurer_bretz_z_raw_cpp(pvec, analyses, hypotheses, edges, weights));
    return rcpp_result_gen;
END_RCPP
}
// calculate_analysis_timing_cpp
DataFrame calculate_analysis_timing_cpp(DataFrame df, DataFrame analyses, DataFrame hypotheses);
RcppExport SEXP _appendMCP_calculate_analysis_timing_cpp(SEXP dfSEXP, SEXP analysesSEXP, SEXP hypothesesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type analyses(analysesSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type hypotheses(hypothesesSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_analysis_timing_cpp(df, analyses, hypotheses));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_appendMCP_sim_pwc_recruitment_cpp", (DL_FUNC) &_appendMCP_sim_pwc_recruitment_cpp, 3},
    {"_appendMCP_sim_pwc_stratified_recruitment_cpp", (DL_FUNC) &_appendMCP_sim_pwc_stratified_recruitment_cpp, 4},
    {"_appendMCP_sim_pb_randomization_cpp", (DL_FUNC) &_appendMCP_sim_pb_randomization_cpp, 2},
    {"_appendMCP_events_at_time_cpp", (DL_FUNC) &_appendMCP_events_at_time_cpp, 4},
    {"_appendMCP_time_at_events_cpp", (DL_FUNC) &_appendMCP_time_at_events_cpp, 4},
    {"_appendMCP_recruited_at_time_cpp", (DL_FUNC) &_appendMCP_recruited_at_time_cpp, 3},
    {"_appendMCP_time_at_recruited_cpp", (DL_FUNC) &_appendMCP_time_at_recruited_cpp, 3},
    {"_appendMCP_responses_at_time_cpp", (DL_FUNC) &_appendMCP_responses_at_time_cpp, 4},
    {"_appendMCP_time_at_responses_cpp", (DL_FUNC) &_appendMCP_time_at_responses_cpp, 4},
    {"_appendMCP_test_pooled_proportions_cpp", (DL_FUNC) &_appendMCP_test_pooled_proportions_cpp, 5},
    {"_appendMCP_test_unpooled_proportions_cpp", (DL_FUNC) &_appendMCP_test_unpooled_proportions_cpp, 5},
    {"_appendMCP_test_logrank_cpp", (DL_FUNC) &_appendMCP_test_logrank_cpp, 5},
    {"_appendMCP_test_stratified_logrank_cpp", (DL_FUNC) &_appendMCP_test_stratified_logrank_cpp, 5},
    {"_appendMCP_test_cmh_cpp", (DL_FUNC) &_appendMCP_test_cmh_cpp, 5},
    {"_appendMCP_cut_data_at_time_cpp", (DL_FUNC) &_appendMCP_cut_data_at_time_cpp, 2},
    {"_appendMCP_update_graph_cpp", (DL_FUNC) &_appendMCP_update_graph_cpp, 3},
    {"_appendMCP_update_p_thresholds_cpp", (DL_FUNC) &_appendMCP_update_p_thresholds_cpp, 4},
    {"_appendMCP_get_maurer_bretz_z_raw_cpp", (DL_FUNC) &_appendMCP_get_maurer_bretz_z_raw_cpp, 5},
    {"_appendMCP_calculate_analysis_timing_cpp", (DL_FUNC) &_appendMCP_calculate_analysis_timing_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_appendMCP(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
