# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sim_pwc_recruitment_cpp <- function(rates, periods, n) {
    .Call(`_appendMCP_sim_pwc_recruitment_cpp`, rates, periods, n)
}

sim_pwc_stratified_recruitment_cpp <- function(enroll_rate, n, n_min_per_stratum = NULL, n_max_per_stratum = NULL) {
    .Call(`_appendMCP_sim_pwc_stratified_recruitment_cpp`, enroll_rate, n, n_min_per_stratum, n_max_per_stratum)
}

sim_pb_randomization_cpp <- function(enroll_data, enroll_rate) {
    .Call(`_appendMCP_sim_pb_randomization_cpp`, enroll_data, enroll_rate)
}

events_at_time_cpp <- function(df, time, ep, strata = NULL) {
    .Call(`_appendMCP_events_at_time_cpp`, df, time, ep, strata)
}

time_at_events_cpp <- function(df, events, ep, strata = NULL) {
    .Call(`_appendMCP_time_at_events_cpp`, df, events, ep, strata)
}

recruited_at_time_cpp <- function(df, time, strata = NULL) {
    .Call(`_appendMCP_recruited_at_time_cpp`, df, time, strata)
}

time_at_recruited_cpp <- function(df, recruited, strata = NULL) {
    .Call(`_appendMCP_time_at_recruited_cpp`, df, recruited, strata)
}

responses_at_time_cpp <- function(df, time, ep, strata = NULL) {
    .Call(`_appendMCP_responses_at_time_cpp`, df, time, ep, strata)
}

time_at_responses_cpp <- function(df, responses, ep, strata = NULL) {
    .Call(`_appendMCP_time_at_responses_cpp`, df, responses, ep, strata)
}

test_pooled_proportions_cpp <- function(df, endpoint, strata, control, test) {
    .Call(`_appendMCP_test_pooled_proportions_cpp`, df, endpoint, strata, control, test)
}

test_unpooled_proportions_cpp <- function(df, endpoint, strata, control, test) {
    .Call(`_appendMCP_test_unpooled_proportions_cpp`, df, endpoint, strata, control, test)
}

test_logrank_cpp <- function(df, endpoint, strata, control, test) {
    .Call(`_appendMCP_test_logrank_cpp`, df, endpoint, strata, control, test)
}

test_stratified_logrank_cpp <- function(df, endpoint, strata, control, test) {
    .Call(`_appendMCP_test_stratified_logrank_cpp`, df, endpoint, strata, control, test)
}

test_cmh_cpp <- function(df, endpoint, strata, control, test) {
    .Call(`_appendMCP_test_cmh_cpp`, df, endpoint, strata, control, test)
}

cut_data_at_time_cpp <- function(df, time) {
    .Call(`_appendMCP_cut_data_at_time_cpp`, df, time)
}

update_graph_cpp <- function(edges, weights, rejected) {
    .Call(`_appendMCP_update_graph_cpp`, edges, weights, rejected)
}

update_p_thresholds_cpp <- function(analyses, hypotheses, edges, weights) {
    .Call(`_appendMCP_update_p_thresholds_cpp`, analyses, hypotheses, edges, weights)
}

get_maurer_bretz_z_raw_cpp <- function(pvec, analyses, hypotheses, edges, weights) {
    .Call(`_appendMCP_get_maurer_bretz_z_raw_cpp`, pvec, analyses, hypotheses, edges, weights)
}

calculate_analysis_timing_cpp <- function(df, analyses, hypotheses) {
    .Call(`_appendMCP_calculate_analysis_timing_cpp`, df, analyses, hypotheses)
}

